### PR TITLE
Features/switches

### PR DESCRIPTION
**Pull request by pietervdvn**
This branch adds:

- Code to make parsing of switches way easier, extensible, flexible and more maintainable
- Piggyback on this go generate documentation from the parser
- The actual (generated) [file containing said documentation.](https://github.com/itinero/idp/blob/features/switches/CommandLineArgs.md)

Before merging, a few clarifications are still needed. To me, it is unclear what the following options are:

- In [ReadShapeFile](https://github.com/itinero/idp/blob/features/switches/src/IDP/Switches/Shape/SwitchReadShape.cs#L50): I do not know what SVC/TVC is
- In [CreateRouterDB](https://github.com/itinero/idp/blob/features/switches/src/IDP/Switches/RouterDb/SwitchCreateRouterDb.cs#L72): What exactly does `keepWayIds`, `allCore`, `simplification` and `normalize` do?
- In [Contract](https://github.com/itinero/idp/blob/features/switches/src/IDP/Switches/RouterDb/SwitchContractRouterDb.cs#L27): `Augment` is unclear to me as well. What is an augmented weight handler? How to specify one?

When fixed, run `IDP --? md=CommandLineArgs.md` to generate the new documentation.

### CODE REVIEW

**Comment by xivk** [comment]
-  SVC/TVC: This is to identity the first and last vertex of every edge in the shape file. The shapefile only has linestrings in it, the edges. To link them together we need to know the first and last vertex id of each edge.
- `keepWayIds` : This keeps the way ids as metadata on an edge.
- `allCore`: Every OSM node is converted to a vertex, not just those at intersections.
- `simplification`: The simplification parameter, this can be used to tune simplification.
- `normalize`: ~~This is control itinero handling duplicate edges between vertices.~~ This is to disable tag normalization, sometimes a set of tags has the exact same meaning, these can be grouped together in one profile.
- Augment: This is used to store both time and distance in the contracted graph. This allows for very quick calculations of time/and distance at the same time.

**Comment by pietervdvn** [comment]
> * SVC/TVC: This is to identity the first and last vertex of every edge in the shape file. The shapefile only has linestrings in it, the edges. To link them together we need to know the first and last vertex id of each edge.

I'm quite lost here - perhaps because I've not really worked with shapefiles yet. Could you give an example of the correct invocation of this flag? I'll add it to the docs too then.

> * `keepWayIds` : This keeps the way ids as metadata on an edge.

In order to be able to reference to the original data source?

> * `allCore`: Every OSM node is converted to a vertex, not just those at intersections.

So this keeps the geometry of the road - e.g. if there is a bend in the road, it will be saved in the routerdb, allowing e.g. correct visualisation afterwards?

> * `simplification`: The simplification parameter, this can be used to tune simplification.

And what exactly does simplification do? It might be worthwhile to state a little what simplifications are performed.

> * `normalize`: ~~This is control itinero handling duplicate edges between vertices~~. This is to disable tag normalization, sometimes a set of tags has the exact same meaning, these can be grouped together in one profile.

Ah, so for example:

`highway=trunk & max_speed = 120` would by all practical accounts be the same as `highway=motorway & max_speed=120` and thus get the same profile number in the table of properties. Setting this flag to true will enable this feature? IIRC the previous behaviour was 'false' by default.

> * Augment: This is used to store both time and distance in the contracted graph. This allows for very quick calculations of time/and distance at the same time.

Does the default behaviour only store time needed then? I interpret the process now as being 'calculate how long the vehicle would travel over a road, based on distance and tags of the road. Then throw away distance and tags, only to keep time'.
With 'augment', distance and tags would be maintained in the routerdb?
And is this tag useful to set in combination with contraction?

**Comment by xivk** [comment]
First of all, keep in mind that these optional parameter are already highly specialized features. 99% of users won't need/use them and there is decent default for all of them. It's a bit overkill to document them in such great detail.

- simplification: this is run on each edge to remove shapepoints that are not useful: https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm
- allcore: by default nodes with two neighbours are not turned into vertices but shapepoints. setting this to true converts all nodes into vertices not just those at intersections.
- keepwayids: yes, exactly
- augment: this is specifically for contraction hierarchies (CH), they usually only store one metric, time or distance. this option make it store both. calculate a matrix of time or distances using contraction hierarchies can be done without reconstructing the actual route but it can only output the metric from the hierarchy. using this option, the CH is augmented with extra data resulting in a matrix of weights that can contain both time and distance. 
- normalization: that's basically true, but the normalization algorithm won't change highway tags, think more about access tags and so on. Sometimes an access tag is implied, sometimes it is added explicitly, the two are equivalent and identity.

**Comment by xivk** [comment]
Oh and these are examples of the SVC and TVC:

https://github.com/itinero/routing/blob/develop/samples/Sample.Shape/car.lua#L6

**Pull request merged**
